-- A direct flight with no connections or stop-overs
--
-- NB A direct flight may stop at an airport before continuing to destination.
--
-- Input: date to fly
--        source and destination airports
--